version: "3"
services:
  ts-restserver:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ts-restserver
    restart: always
    ports:
    - "5000:5000"
    environment:
      PORT: 5000
      DB_DIALECT: postgres
      DB_USER: root
      DB_PASS: root
      DB_HOST: 172.18.0.2
      DB_PORT: 5432
      DB_NAME: node    
