version: "3.8"
services:
  ts-restserver:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ts-restserver
    restart: always
    ports:
      - "5000:5000"
    networks:
      - aplicaciones
    environment:
      PORT: 5000
      DB_DIALECT: postgres
      DB_USER: root
      DB_PASS: root
      DB_HOST: local_postgres
      DB_PORT: 5432
      DB_NAME: node_server
networks:
  aplicaciones:
    external:
      name: aplicaciones
  
